[
  {
    _id: {
      $oid: "63d4aa9a63a7546d5dfa688c"
    },

    title: "Bachelor of Science [B.S] (Computer Engineering - Software)",
    info: "    The University of Alberta offers a BSc in Computer Engineering Software for a duration of 4years.    It is an on-campus, co-op program offered on a full-time basis.    This program provides students with the skills and knowledge needed to succeed in the rapidly evolving field of software engineering and development.    Students will build on their foundational knowledge in computing by studying areas such as discrete and continuous mathematics, physical science, logic, and engineering design principles through to application and development of software systems of all sizes.    This degree program can be taken as a co-op (co-operative education) program.    Through the co-op program, students will have the opportunity to complete paid, supervised work terms throughout the degree program.    Throughout the degree, students have the opportunity to gain hands-on experience, participate in research, and contribute to team projects both inside and out of the classroom.    Most co-op programs include five work terms lasting four months each, in addition to the usual eight terms (four years) of full-time study. Therefore, co-op programs require five years to complete.    Every year, students in the Faculty of Engineering have access to more than $1.5 million in scholarships.    The Faculty of Engineering at the University of Alberta is home to approximately 200 faculty members, 150 professional and support staff, and 120 research professional and operational staff.    The Faculty of Engineering is widely recognized as one of the top engineering schools in Canada, with globally renowned professors, state-of-the-art labs and teaching spaces, and highly specialized facilities and areas of research.    Job opportunities after BSc in Computer Engineering Software are Computer Engineer, Software Engineer, etc.  ",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹2446006₹2446006₹2446006₹2446006Health Insurance₹7832₹7832₹7832₹7832Books and supply₹72852₹72852₹72852₹72852Total Fees₹2526689₹2526689₹2526689₹2526689",
    exams: "This program does not allow admission directly from high school. If students are applying directly from high school, they must enter into a qualifying first year of Engineering.    Students have to complete a preprofessional Study of 1 year.    Students should hold an English Language Proficiency test score.Indian Student Eligibility:Indian students are eligible to apply if they meet one of the following eligibility criteria:    Complete International Baccalaureate (IB) or Advanced Placement (AP) courses.    Secured a minimum of 70% marks in one of these certificates: All India Senior School Certificate, Higher Secondary School Certificate, Intermediate Certificate, Indian School Certificate.    Completed grade 11 and grade 12 with 70% marks.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.  ",
    __v: 0
  },
  {
    _id: {
      $oid: "63d4ab5087cf283cd57c97c1"
    },
    title: "Bachelor of Engineering [B.Eng] (Software Engineering)",
    info: "    Software engineers investigate tools, methods, theories, and techniques to support the development of software. At present, our active areas of focus include application frameworks, software reverse engineering, reengineering and reuse, software engineering for web-based applications, and software processes for small organizations.    Service Systems Research Group: focuses on the technical and socioeconomic concerns around building software systems for the purpose of service delivery.  ",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹2446006₹2446006₹2446006₹2446006Health Insurance₹7832₹7832₹7832₹7832Books and supply₹72852₹72852₹72852₹72852Total Fees₹2526689₹2526689₹2526689₹2526689",
    exams: "Students must provide a certified copy of the diploma or high school degree to get admission to this program.    Students should hold an English Language Proficiency test score.Indian Student Eligibility:Indian students are eligible to apply if they meet one of the following eligibility criteria:    Complete International Baccalaureate (IB) or Advanced Placement (AP) courses.    Secured a minimum of 70% marks in one of these certificates: All India Senior School Certificate, Higher Secondary School Certificate, Intermediate Certificate, Indian School Certificate.    Completed grade 11 and grade 12 with 70% marks.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.  ",
    __v: 0
  },
  {
    _id: {
      $oid: "63d4ab5187cf283cd57c97c3"
    },
    title: "Bachelor of Science [B.S] (Engineering Physics - Nanoengineering)",
    info: "    The Engineering Physics Nanoengineering Option provides an introduction to the physics problems associated with engineering at the nanoscale level.    Students enrolled in this program have a wealth of resources at their disposal, including the Micromachining and Nanofabrication Facility, and the recently established undergraduate nanotechnology lab.  ",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹2446006₹2446006₹2446006₹2446006Health Insurance₹7832₹7832₹7832₹7832Books and supply₹72852₹72852₹72852₹72852Total Fees₹2526689₹2526689₹2526689₹2526689",
    exams: "Following are the requirements for admission:    Overall 60% is required along withFirst Class Standing/Division or grade ofB in 11 and 12.    Students needed to obtain official copies of all transcripts (mark sheets) and final degree certificates from post-secondary institutions in the original language as well asin English.    This program does not allow admission directly from high school.If studentsare applying directly from high school, theymust enter into a qualifying first year of Engineering.Indian Student Eligibility:Indian students are eligible to apply if they meet one of the following eligibility criteria:    Complete International Baccalaureate (IB) or Advanced Placement (AP) courses.    Secured a minimum of 70% marks in one of these certificates:      All India Senior School Certificate    Higher Secondary School Certificate    Intermediate Certificate    Indian School Certificate        Completed grade 11 and grade 12 with70% marks.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.  ",
    __v: 0
  },
  {
    _id: {
      $oid: "63d4ab5187cf283cd57c97c9"
    },
    title: "Bachelor of Science [B.S] (Computer Engineering - Nanoscale System Design)",
    info: "This program gives studentsthe opportunity to focus on the emerging field of nanotechnology, giving studentsan introduction to the processes involved in the fabrication of nanoscale integrated circuits and in designing the tools necessary for the mass production of nanoscale systems.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹2446006₹2446006₹2446006₹2446006Health Insurance₹7832₹7832₹7832₹7832Books and supply₹72852₹72852₹72852₹72852Total Fees₹2526689₹2526689₹2526689₹2526689",
    exams: "Following are the requirements for admission:    Overall 60% is required along withFirst Class Standing/Division or grade ofB in 11 and 12.    Students needed to obtain official copies of all transcripts (mark sheets) and final degree certificates from post-secondary institutions in the original language as well asin English.    This program does not allow admission directly from high school.If studentsare applying directly from high school, theymust enter into a qualifying first year of Engineering.  ",
    __v: 0
  },
  {
    _id: {
      $oid: "63d4ab5187cf283cd57c97c5"
    },
    title: "Bachelor of Science [B.S] (Engineering Physics)",
    info: "    BSc inEngineering Physics at the University of Alberta allows students to complete this course in 4years.    It is an on-campus program offered on a full-time basis.    The program consists of a variety of engineering disciplines together with mathematics, applied physics, and the natural sciences.    Engineering physicists are accomplishing breakthroughs and innovations in a variety of fields by applying cutting-edge physics research to new and existing technologies.    The student-facultyratio of this program is 21:1.    Students get the opportunities to apply for scholarships, fellowships, awards, and grants both internally and externally.    This program in UofA starts with a strong foundation in mathematics and physics and builds upon these principles through active research projects in areas such as fusion energy, microelectronics, robotics systems, and fiber-optic communications.    It offers a wide range of opportunities upon graduation, preparing studentsto meet unique engineering challenges.    As part of this program, students also get the opportunity to complete their specialization course in Nanoengineering program option.    The Faculty of Engineering's mission is to:      produce engineering graduates of choice for employers and post-graduate schools and to produce graduates who can be leaders in engineering design and research.    produce nationally and internationally recognized engineering research.    provide high-quality service to the engineering profession and the external community.        Throughout the degree, students will have the opportunity to gain hands-on experience, participate in research, and contribute to team projects both inside and out of the classroom.    The University of Alberta is one of the top 5 universities in Canadawith state-of-the-art teaching and research facilities, award-winning professors, a diverse and welcoming community.    The Faculty of Engineering is widely recognized as one of the top engineering schools in Canada, with globally renowned professors, state-of-the-art labs and teaching spaces, and highly specialized facilities and areas of research.    Job opportunities after BSc in Chemical Engineering are Engineer,Engineering Physicist, etc and the average salary goes up to 43,000 USD.  ",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹2446006₹2446006₹2446006₹2446006Health Insurance₹7832₹7832₹7832₹7832Books and supply₹72852₹72852₹72852₹72852Total Fees₹2526689₹2526689₹2526689₹2526689",
    exams: "This program does not allow admission directly from high school. If students are applying directly from high school, they must enter into a qualifying first year of Engineering.    Students have to complete the English (Literature and Composition), Calculus, Chemistry, Mathematics and Physics subjects courses to get admission in this program.    Students have to complete a preprofessional Study of 1 year.    Students should hold an English Language Proficiency test score.Indian Student Eligibility:Indian students are eligible to apply if they meet one of the following eligibility criteria:    Complete International Baccalaureate (IB) or Advanced Placement (AP) courses.    Secured a minimum of 70% marks in one of these certificates:      All India Senior School Certificate    Higher Secondary School Certificate    Intermediate Certificate    Indian School Certificate        Completed grade 11 and grade 12 with 70% marks.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.  ",
    __v: 0
  },
  {
    _id: {
      $oid: "63d4ab5187cf283cd57c97c7"
    },
    title: "Bachelor of Science [B.S] (Computing Science - Software Practice)",
    info: "The B.Sc. in Software Practice is for students who are interested in all aspects of building software.    The program has a broad range of courses to develop depth in programming, algorithms, hardware, software design, user interfaces, project management, and business issues. Even then, almost half of the courses are options.  ",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹1826764₹1826764₹1826764₹1826764Health Insurance₹7832₹7832₹7832₹7832Books and supply₹72852₹72852₹72852₹72852Total Fees₹1907447₹1907447₹1907447₹1907447",
    exams: "This program does not allow admission directly from high school. If students are applying directly from high school, they must enter into a qualifying first year of Engineering.    Students have to complete the English Language, Calculus, Chemistry, Mathematics, and Physics subjects courses to get admission in this program.    Students have to complete a preprofessional Study of 1 year.    Students should hold an English Language Proficiency test score.Indian Student Eligibility:      Indian students are eligible to apply if they meet one of the following eligibility criteria:      Complete International Baccalaureate (IB) or Advanced Placement (AP) courses.    Secured a minimum of 70% marks in one of these certificates:      All India Senior School Certificate    Higher Secondary School Certificate    Intermediate Certificate    Indian School Certificate        Completed grade 11 and grade 12 with 70% marks.      Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.      ",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a595a54f5d41a53f3f13"
    },
    title: "Bachelor of Applied Science [B.ASc] (Civil Engineering)",
    info: "The Bachelor of Applied Science inCivil Engineering is a 4-year program at the University of British Columbia(UBC).The common civil engineering projects include buildings, plants, roads, water supply, and sewer systems, and flood and traffic control. Civil engineers design structures and alter geography to suit human needs.In fourth-year students can complete the Engineering Capstone Design Project, where they design a project – which can be a specialized area of engineering – in response to an actual engineering problem.ThroughEngineering Co-operative Education, students can work in BC, across Canada, or around the world while gaining international insight and developing technical skills, industry networks, and mentoring opportunities with professionals.This program focus on main following areas:Engineering Drawing and CAD/CAMOrthographicFundamentals of Sustainable Engineering DesignTheorySystem DynamicsInstrumentation and Data AnalysisCivil Engineering Materials StructureEarthquake EngineeringA UBC education will introduce students to people and ideas from around the world, open doors to new opportunities, and take them places they never imagined.The Student to Faculty Ratio is 18:1 which resolves the interaction Problem.The University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a60ee2b81457add24c08"
    },
    title: "Bachelor of Applied Science [B.ASc] (Biomedical Engineering)",
    info: "The Bachelor of Applied Science inBiomedical Engineering is a 4-year program at the University of British Columbia(UBC).Students will gain a strong understanding of biology, human anatomy, and physiology, and develop the skills required to apply this knowledge in engineering design contexts and solve engineering problems.This program focus on main following areas:Introduction to biomedical engineeringBiomedical EngineeringCircuits and Electromagnetics with Application to Biomedical EngineeringBiomechanicsIntroduction to BioinformaticsEconomics of Healthcare SolutionsAs a Biomedical Engineering student, they will have classes, teaching laboratories, capstone projects, and studio sessions in various Faculty of Applied Sciences buildings on UBC's Vancouver campus.Theprogram combines interests in life sciences with engineering and therefore focuses on processes in the fields of biotechnology and biomedical engineering.The student to faculty ratio is 18:1 which resolves the interaction problem.The Biomedical Engineering program also gives an excellent foundation for graduate studies or professional degrees in medicine, engineering, pharmacy, law, or business.Students will be specializing in one of four streams:Biomechanics and biomaterialsCellular and molecular bioengineeringBiomedical systems and signalsBiomedical informaticsThe University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses .Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7e8e92a15ad48da2773"
    },
    title: "Bachelor of Applied Science [B.ASc] (Computer Science - Software Engineering)",
    info: "The Computer Science BSc program includes the general Science degree requirements, with further choices in mathematics courses, a thorough grounding in computer software design, and a broad choice of other studies in computing.It gives studentsthe freedom to pursue interests both within and outside Computer Science.They may select theirelectives from many departments, from Psychology to Commerce, and Music to Electrical Engineering. Options include Software Engineering, or a Combined Major or Honours with sciences, mathematics, or statistics.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7e9e92a15ad48da2775"
    },
    title: "Bachelor of Applied Science [B.ASc] (Mining Engineering)",
    info: "The Bachelor of Applied Science in Mining Engineering is a 4-year program at the University of British Columbia(UBC).Mining Engineering is concerned with the extraction and processing of ores containing valuable minerals or metals.This program focus on main following areas:Introduction to EngineeringChemistry for EngineeringIntroductory Physics for EngineersTechnical CommunicationEngineering MaterialsProfessional Engineering PracticeThe Mining Engineering program integrates courses on engineering principles, earth sciences, and mining and mineral processing with content covering health, management, economics, and environmental and social issues.The student to faculty ratio is 18:1 which resolves the interaction problem.Students will graduate not only with expertise in their chosen field, but with the skills they need to continue growing, learning, and evolving with their career over time.The University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7e9e92a15ad48da277b"
    },
    title: "Bachelor of Commerce [B.Com] (Business Technology Management)",
    info: "Information systems are at the heart of all significant commercial enterprises, particularly in the age of booming e-commerce. The Business Technology Management program will equip you with both the technical expertise and the analytic business awareness to thrive in this field.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3530469₹3530469₹3530469₹3530469Total Fees₹3530469₹3530469₹3530469₹3530469",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7e9e92a15ad48da2779"
    },
    title: "Bachelor of Applied Science [B.ASc] (Environmental Engineering)",
    info: "The Bachelor of Applied Science inEnvironmental Engineering is a 4.5-year (nine-semester) program at the University of British Columbia(UBC).This is a joint degree between UBC and the University of Northern British Columbia (located in Prince George, BC).The program starts with a two-year foundation in mathematics, basic sciences, and environmental sciences from UNBC.The third and fourth years offer training in engineering fundamentals, engineering analysis, and engineering design, through courses in Civil Engineering and Chemical andBiological Engineering at UBC.The final term at UNBC exposes students to practical environmental engineering problems.This program focus on main following areas:Introduction to EngineeringChemistry for EngineeringComputation, Programs, and ProgrammingEnvironmental Engineering LaboratoryWater Pollution ControlThe Environmental Engineering program is based on a unique collaboration between UNBC and UBC, which capitalizes on the strength of UNBC in Environmental Science and the strength of UBC in Engineering.The student to faculty ratio is 18:1 which resolves the interaction problem.Students will graduate not only with expertise in their chosen field, but with the skills they need to continue growing, learning, and evolving with their career over time.The University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7e9e92a15ad48da2777"
    },
    title: "Bachelor of Science [B.S] (Biotechnology)",
    info: "Biotechnology is the scientific manipulation of living organisms, especially at the molecular genetic level.The combination of theoretical and practical studies focusing on microbiology and related disciplines is designed for students planning to work in the biotechnology sector. Honours Biotechnology is offered in cooperation with the BC Institute of Technology (BCIT).Studentsmust complete a 30-credit first-year program at UBC before transferring to BCIT for two years.Then theyreturn to UBC for two years of academic and co-op work terms.Some applications of biotechnology include the genetic engineering of food crops for disease or pest resistance, creating new medicines, and, in the environmental sector, the development of bacteria that consume toxic chemicals and reduce pollution.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹2810569₹2810569₹2810569₹2810569Total Fees₹2810569₹2810569₹2810569₹2810569",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7e9e92a15ad48da277d"
    },
    title: "Bachelor of Applied Science [B.ASc] (Engineering Physics)",
    info: "The Bachelor of Applied Science inEngineering Physics is a 5-year program at the University of British Columbia(UBC).Students will build a solid foundation in applied physics and a blend of electrical and mechanical engineering while gaining extensive engineering design experience.The five-year Engineering Physics program gives studentsthe skills and experience needed to develop new technology and interdisciplinary engineering projects.This program focus on main following areas:Introduction to EngineeringChemistry for EngineeringIntroductory Physics for EngineersPrinciples of Software ConstructionLinear CircuitsDigital Systems and MicrocomputersMechanics of MaterialsElectronic CircuitsProfessional Engineering PracticeThe academic program normally boosts with technical experience, and protected time for technical work terms is built into the curriculum.The student to faculty ratio is 18:1 which resolves the interaction problem.The UBC Sustainability Solutions Applied Physics Laboratory has unique research projects, such as the UBC Solar Canopy group, aiming to explore the potential of electromagnetics, for practical environmentally aware solutions.Students will graduate not only with expertise in their chosen field, but with the skills they need to continue growing, learning, and evolving with their career over time.The University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Year 5Tuition Fees₹3505092₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7eae92a15ad48da277f"
    },
    title: "Bachelor of Applied Science [B.ASc] (Electrical Engineering)",
    info: "The Bachelor of Applied Science inElectrical Engineeringis a 4-year program at the University of British Columbia(UBC).Students learn essential skillsin electronics, circuit analysis, andelectromagnetics, and after their first year,customize theirprogram by taking specialized courses innanotechnology, biomedical engineering,or renewable energy.Electrical engineering consists of three eight-month academic sessions either the first-year engineering ora transfer program from the first-year science.The second-year is common to both Electrical Engineering and Computer EngineeringThe Student to Faculty Ratio is 18:1 which resolves the interaction Problem.Each year, several of the students win scholarship awards and they design teams regularly win prizes in regional, national, and international design competitions.Students will graduate not only with expertise in their chosen field, but with the skills they need to continue growing, learning, and evolving with their career over time.The University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7eae92a15ad48da2781"
    },
    title: "Bachelor of Applied Science [B.ASc] (Chemical and Biological Engineering)",
    info: "The Bachelor of Applied Science inChemical and Biological Engineering is a 4-year program at the University of British Columbia(UBC).This program gives an opportunity for students to combine interests in life sciences with engineering, and therefore focuses on processes in the fields of biotechnology and biomedical engineering.This program focus on main following areas:Introductory Physics for EngineersBiology of the CellMaterial and Energy BalancesKinetics and Reactor DesignBiological Process and Product DesignThis programconsists of combining lectures, hands-on lab activities, research, industry visits, and design experiences to providestudents the balance of practical and analytical skills needed to become successful, competent engineers.Theprogram combines interests in life sciences with engineering and therefore focuses on processes in the fields of biotechnology and biomedical engineering.The student to faculty ratio is 18:1 which resolves the interaction problem.Some students graduating from this program continue their studies in the medical field.Students are eligible, after the appropriate industrial experience, for registration as Professional Engineers.Students will graduate not only with expertise in their chosen field, but with the skills they need to continue growing, learning, and evolving with their career over time.The University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses (recommended, but not required)Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2a7eae92a15ad48da2783"
    },
    title: "Bachelor of Applied Science [B.ASc] (Biomedical Engineering)",
    info: "The Bachelor of Applied Science inBiomedical Engineering is a 4-year program at the University of British Columbia(UBC).Students will gain a strong understanding of biology, human anatomy, and physiology, and develop the skills required to apply this knowledge in engineering design contexts and solve engineering problems.This program focus on main following areas:Introduction to biomedical engineeringBiomedical EngineeringCircuits and Electromagnetics with Application to Biomedical EngineeringBiomechanicsIntroduction to BioinformaticsEconomics of Healthcare SolutionsAs a Biomedical Engineering student, they will have classes, teaching laboratories, capstone projects, and studio sessions in various Faculty of Applied Sciences buildings on UBC's Vancouver campus.Theprogram combines interests in life sciences with engineering and therefore focuses on processes in the fields of biotechnology and biomedical engineering.The student to faculty ratio is 18:1 which resolves the interaction problem.The Biomedical Engineering program also gives an excellent foundation for graduate studies or professional degrees in medicine, engineering, pharmacy, law, or business.Students will be specializing in one of four streams:Biomechanics and biomaterialsCellular and molecular bioengineeringBiomedical systems and signalsBiomedical informaticsThe University of British Columbia ranked as the 45th best university in the world in the QS World University Rankings.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3505092₹3505092₹3505092₹3505092Total Fees₹3505092₹3505092₹3505092₹3505092",
    exams: "Graduation from high schoolMinimum of 70% in Grade 11 or Grade 12 English (or their equivalents)At least six academic/non-academic Grade 12 courses .Indian student eligibility:General admission requirements for Indian students are:Graduation from a university-preparatory program at a senior secondary school:Higher Secondary School Certificate awarded on completion of Standard XII.Certificates must be official. Photocopies are acceptable if certified by the school principal, head, or counselor. Notarized copies are not acceptable.Degree-specific requirements:ScienceMath (Standard XII)Chemistry (Standard XII)Physics (Standard XII) (Physics may be waived with grades of A in Senior Math and Senior Chemistry)Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test to get admission to this program.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55743ec1da33e5b5c621f"
    },

    title: "Bachelor of Science [B.S] (Software Engineering)",
    info: "University of Calgary offers a BScin Software Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Engineering in Software Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Software engineers use their specialized knowledge to develop, install, validate, and maintain software systems.As software engineering students, theywill gain theoretical foundations and plenty of design and research experience so theycan achieve success in thefield.During the course of thestudies, much of thelearning will occur in class, during tutorials, and through designing a complete industrial process for a specific product.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications, and design.Some of the courses in this program are:Computing for EngineersEngineering Design and CommunicationGeneral Chemistry for EngineersSoftware Analysis And Design​Calculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes after completing this program up to80,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "The candidate must present a minimum of 65 percent in English or equivalent.The candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission to this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55867ed984bfc9b274be7"
    },
    title: "Bachelor of Science [B.S] (Electrical Engineering)",
    info: "University of Calgary offers a BSc in Electrical Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Electrical Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Electrical engineers are involved in almost every facet of our high-tech world. They explore and develop new and innovative technologies through the research and manipulation of electrical phenomena.During the course of thestudies, much of thelearning will occur in class, during tutorials, and through working on an advanced-level project in specialized research-and-design courses.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications and design.Some of the courses in this program are:Computing for EngineersComputing ToolsEngineering Design and CommunicationLinear Methods ICalculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes upto89,900 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "Candidate must present a minimum 65 percent in English or equivalent.Candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission in this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55867ed984bfc9b274be9"
    },
    title: "Bachelor of Science [B.S] (Energy Engineering)",
    info: "University of Calgary offers a BSc in Energy Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Energy Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Energy Engineers find new, efficient, and sustainable ways to supply the world with energy.Energy Engineering program addresses the energy industry's need for engineering graduates who bring a unique mix of technology and engineering science skills and knowledge to the workplace, which sets them apart from graduates of traditional engineering programs.This fully accredited transfer program allows studentsto combine an energy-related engineering technology diploma from an approved polytechnic institute with an engineering degree from the University of Calgary's Schulich School of Engineering within as little as 24 months of study.Some of the courses in this program are:Alternative Energy SystemsEngineering Design and Energy PolicyIntroduction to Reservoir EngineeringLife Cycle AssessmentPetroleum Production EngineeringThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes up to65,745 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "Candidate must present a minimum 65 percent in English or equivalent.Candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission in this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55867ed984bfc9b274bed"
    },
    title: "Bachelor of Science [B.S] (Geomatics Engineering)",
    info: "University of Calgary offers a BSc in Engineering in Geomatics Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Engineering in Geomatics Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Geomatics engineering is an information technology discipline that deals with the acquisition, modelling, analysis and management of spatial data.Geomatics is one of the fastest growing information sciences, which means the techniques and skills students will gain will be in high demand within a wide range of real-world work environments.During the course of thestudies, much of thelearning will occur in class, during tutorials, and through working on advanced-level projects.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications and design.Some of the courses in this program are:Computing for EngineersEngineering Design and CommunicationGeneral Chemistry for EngineersSpectral Analysis in GeomaticsCalculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes up to64,195 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "Candidate must present a minimum 65 percent in English or equivalent.Candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission in this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55867ed984bfc9b274beb"
    },
    title: "Bachelor of  Engineering[B.Eng] (Chemical Engineering)",
    info: "University of Calgary offers a BSc in Chemical Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Chemical Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Chemical engineering is one of the most broadly-based engineering disciplines, which means the techniques and skills students will gain will be directly applicable to a wide range of real world work environments.During the course of the studies, much of the learning will occur in class, during tutorials, and through designing a complete industrial process for a specific product.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications and design.Some of the courses in this program are:Chemical Engineering Process CalculationComputing for EngineersEngineering Design and CommunicationGeneral Chemistry for EngineersCalculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes upto80,743 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "Candidate must present a minimum 65 percent in English or equivalent.Candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission in this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55868ed984bfc9b274bef"
    },
    title: "Bachelor of Science [B.S] (Oil and Gas Engineering)",
    info: "University of Calgary offers a BSc in Engineering in Oil and Gas Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Engineering in Oil and Gas Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Oil and gas engineering involves the production of oil and gas in an economical and environmentally safe manner.The technical knowledge and hands-on experience students will gain in this program are specific to industry requirements, so theycan be sure theirdegree will be relevant to theirchosen field.During the course of thestudies, much of thelearning will occur in class, during tutorials, and through completing a team-based design course in theirfourth year.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications and design.Some of the courses in this program are:Computing for EngineersEngineering Design and CommunicationGeneral Chemistry for EngineersIntroduction to Flow in Porour Materials​Calculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes up to72,475 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹1954316₹1954316₹1954316₹1954316Health Insurance₹20034₹20034₹20034₹20034Books and supply₹18213₹18213₹18213₹18213Compulsory Fees₹48287₹48287₹48287₹48287Miscellaneous expenses₹328805₹328805₹328805₹328805Total Fees₹2369633₹2369633₹2369633₹2369633",
    exams: "Candidate must present a minimum 65 percent in English or equivalent.Candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission in this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55868ed984bfc9b274bf3"
    },
    title: "Bachelor of Science [B.S] (Software Engineering)",
    info: "University of Calgary offers a BScin Software Engineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Engineering in Software Engineering consists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Software engineers use their specialized knowledge to develop, install, validate, and maintain software systems.As software engineering students, theywill gain theoretical foundations and plenty of design and research experience so theycan achieve success in thefield.During the course of thestudies, much of thelearning will occur in class, during tutorials, and through designing a complete industrial process for a specific product.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications, and design.Some of the courses in this program are:Computing for EngineersEngineering Design and CommunicationGeneral Chemistry for EngineersSoftware Analysis And Design​Calculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes after completing this program up to80,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "The candidate must present a minimum of 65 percent in English or equivalent.The candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission to this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d55868ed984bfc9b274bf1"
    },
    title: "Bachelor of Science [B.S] (Civil Engineering)",
    info: "University of Calgary offers a BSc in CivilEngineering with a duration of 4 years.This programis offered on a full-time basis and delivered on-campus.BSc in Civil Engineeringconsists of 24units.Students will access engineering career advisors and gain valuable full-time paid engineering work experience through a 12-16 month placement.Students will have study abroad opportunities in this program.Civil engineering involves the conception, design, construction, operation, maintenance and management of many structures and systems vital to the public.During the course of thestudies, much of the learning will occur in class, during tutorials, and through the completion of a full-year design project.This fully accredited program features a common first year, which consists of 10 courses in mathematics, sciences, computing, engineering principles, communications and design.Some of the courses in this program are:Computing for EngineersEngineering Design and CommunicationGeneral Chemistry for EngineersTools for Civil Engineering Design​Calculus for Engineers and ScientistsThe University of Calgary ranked in 6thplace in Canada by Research Infosource in 2018.The University offers small class sizesthat provide close research interaction with their supervision.The Faculty of the department have received global recognition by winning awards like federalawards, Provincial awards,Indigenous awards,etc.The average salary goes upto88,700 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fee₹1010336₹1010336₹1010336₹1010336Books and supplies₹86026₹86026₹86026₹86026Health Insurance₹4675₹4675₹4675₹4675Total Fees₹1101037₹1101037₹1101037₹1101037",
    exams: "Candidate must present a minimum 65 percent in English or equivalent.Candidate must present a minimum 2.00 GPA in a transferrable post-secondary English course.Students should achievea minimum of 2.00 cumulative GPA on the most recent 12 units from another post-secondary institution.Students must be qualified inIELTSorTOEFLto get admission in this program.Indian Student Eligibility:The student hasgraduated from senior secondary school or equivalent.Minimum 4 major subjects in 12th Grade, including English, with an average of 70% and no course less than 65%.",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b4ab0c273a6c1afcff4f"
    },

    title: "Bachelor of Engineering [B.Eng] (Mechanical Engineering)",
    info: "Bachelor of Engineering inMechanical Engineeringat McGill Universityallows students to complete this programin 4years.Students needto complete 90credits successfully to graduate from this program.Undergraduate students inMechanical Engineeringcan take Aeronautical Engineering concentration.The Bachelor's in Mechanical Engineering at McGill University offers advanced training in the critical, historical, and theoretical analysis of:Aerodynamics and fluid mechanicsCombustion and energy systemsDesign and manufacturingDynamics and controlMaterials and structuresIn collaboration with theMcGill Institute for Aerospace Engineering(MIAE), the goal of the Mechanical EngineeringAeronautical Concentrationis to foster interest in Aerospace Engineering among undergraduate students and awareness of the multi-disciplinary and multi-cultural environment in which they may work as future engineers working in the Aerospace Industry.Mechanical engineers at McGill University are traditionally concerned with the conception, design, implementation, and operation of mechanical systems.The students to faculty ratio for this Mechanical Engineeringprogram is 16:1.The job opportunities after graduation in McGill's Mechanical Engineeringprogramthat students will get are:AerospaceengineerAutomotiveengineerContracting civilengineerControl and instrumentationengineer,etc., with anaverage salary of 37,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission in McGill's Mechanical Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission in McGill's Mechanical Engineering Program.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a10c1cb06c264742aa"
    },
    title: "Bachelor of Engineering [B.Eng] (Software Engineering)",
    info: "Bachelor of Engineering in SoftwareEngineeringat McGill University allows students to complete this programin 4years.Students needto complete 97credits successfully to graduate from this program.McGill's Software Engineering program offers students the opportunity to focus their studies on the skills needed to design and develop complex software systems.This Software Engineering field is an emerging field of engineering,a major component of the growing Information Technology (IT) sector of the economy, in which the demand for qualified personnel continues to outstrip supply.Graduates of McGill's Software Engineeringprogram will have a solid foundation for careers in the software industry.The Bachelor's in SoftwareEngineering at McGill University offers advanced training in the critical, historical, and theoretical analysis of:Software Development ProjectDesign and Analysis of AlgorithmsOperating System FundamentalsSoftware DesignSoftware Engineering TestingIn addition to technical complementary courses, students take general complementary courses in social sciences, management studies, and humanities. These courses allow students to develop specific interests in areas such as psychology, economics, management, or political science at McGill University.The Software Engineering Minor will prepare engineering students for a career in software engineering.It will provide a foundation in basic computer science, computer programming, and software engineering practice.The students to faculty ratio for this Bachelor of Engineering in Software Engineeringprogram is 16:1.The job opportunities after graduating from this software Engineeringprogram forstudentsare:Embedded Systems EngineerPlatform and Infrastructure EngineerSoftware Architecture Engineer,etc., with anaverage salary of 37,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission in McGill's Software Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission in McGill's SoftwareEngineering Program.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a20c1cb06c264742ac"
    },
    title: "Bachelor of Engineering [B.Eng] (Civil Engineering)",
    info: "Bachelor of Engineering inCivil Engineeringat McGill Universityallows students to complete this programin 4years.Students needto complete 120credits successfully to graduate from this Civil Engineeringprogram.Students are exposed to both theoretical and practical issues of both hardware and software in well-equipped laboratories.The Bachelor's in Civil Engineeringoffers advanced training in the critical, historical, and theoretical analysis of:​Experimental Designs 1Bioprocesses for Wastewater Resource RecoveryTheory: Water / Wastewater TreatmentPrinciples of ToxicologyAdvanced Statistics 1Environmental Data AnalysisIn addition to technical complementary courses, students in the Civil Engineeringprogram take general complementary courses in social sciences, management studies, and humanities.Civil engineers use and develop modern technology to meet the needs ofchanging society.Concerns for environmental quality, energy conservation, infrastructure restoration, and public safety now shape the role of civil engineers.The introduction of advanced materials, computer-aided and communication-based technologies for planning, design, and management are changing the way civil engineers practice.In the area of environmental protection, civil engineers continue their longstanding work on water and waste treatment and management for growing urban populations and industries, but today they also focus on areas such as ecosystem restoration, waste reduction, recycling, and air pollution abatement.The students to faculty ratio for this Civil Engineeringprogram at McGill Universityis 16:1.The job opportunities after this Civil Engineeringprogram that students get at McGill University are:Analytical chemistEnergy managerEnvironmentalengineerManufacturingengineerMaterialsengineer, etc., with anaverage salary of 37,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission at McGill University in this Civil Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission at McGill University'sCivil EngineeringProgram.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a20c1cb06c264742ae"
    },
    title: "Bachelor of Engineering [B.Eng] (Bioresource Engineering)",
    info: "Bioresource Engineering is an interdisciplinary program that integrates engineering, design and the biological sciences. It is a unique profession that applies engineering principles to the enhancement and sustainability of the world's natural resources. Bioresource Engineers seek solutions to problems that involve plants, animals and the environment.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meet the following requirements for admission in McGill'sEngineering program:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31 (Maths & Science subscores ≥ 29, others ≥ 27); orSAT: EB Read & Writing 700, Math 700 and Subject Tests: 680 in each subjectStudents must have basic knowledge in Pre-calculus, Chemistry, and Physics",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a20c1cb06c264742b4"
    },
    title: "Bachelor of Engineering [B.Eng] (Mining Engineering)",
    info: "Bachelor of Engineering inMining Engineeringat McGill Universityallows students to complete this programin 4years.Students needto complete 97credits successfully to graduate from this Mining Engineeringprogram.Students are exposed to both theoretical and practical issues of both hardware and software in well-equipped laboratories.The Bachelor's in Mining Engineeringoffers advanced training in the critical, historical, and theoretical analysis of:GeomechanicsMining EnvironmentsStrategic Mine Planning and OptimizationStochastic ModellingOperations ResearchRock MechanicsIn addition to technical complementary courses, students in the Mining Engineeringprogram take general complementary courses in social sciences, management studies, and humanities.Mining Engineering is a complex and interdisciplinary field involving elements of geological, civil, mechanical, and materials engineering.A Professional Mining Engineer can plan, design, organize and supervise the development of mines, mine facilities, systems and equipment, and can also prepare and supervise the extraction of metallic or non-metallic minerals and ore from underground or surface mines.The students to faculty ratio for this Mining Engineeringprogram at McGill Universityis 16:1.The job opportunities after this Mining Engineeringprogram that students get at McGill University are:Mining Engineer – GraniteMining Engineering TechniciansResearch Engineers- Data MiningDeputy Chief Mechanical – Metals & MiningAssistant Mining EngineerMining Engineer / Mine PlannerTechnical Consultant- Mining Industries, etc., with anaverage salary of47,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission at McGill University in this Mining Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission at McGill University'sMining EngineeringProgram.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a20c1cb06c264742b0"
    },
    title: "Bachelor of Science [B.S] (Software Engineering)",
    info: "The B.Sc. Liberal program is a great way to combine a core of Computer Science or Software Engineering with a breadth option which could be a minor or major concentration from a wide variety of areas. As just one example, if you are interested in studying Computer Science or Software Engineering and also preparing for medical school or life science interdisciplinary studies, you could combine your Computer Science Core Science Component with the Interdisciplinary Minor in Life Sciences.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission in McGill's Software Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission in McGill's SoftwareEngineering Program.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency throughIELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a20c1cb06c264742b2"
    },
    title: "Bachelor of Engineering [B.Eng] (Agricultural Engineering)",
    info: "The Agricultural Engineering stream is the closest to our traditional Agricultural Engineering program. It is also referred to as the \"Food Production Machinery and Buildings\" stream. This stream focuses on providing engineering support for agricultural industries and agricultural enterprises. This includes the design, construction, functioning, etc. of agricultural machines, structures, and other infrastructure such as waste treatment facilities, irrigation and drainage systems, and storage buildings and methods.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Following Documents are required to attend this program:Statement of Purpose (SOP)Letter of Recommendation (LOR)Resume/CVAcademic Documents",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a20c1cb06c264742b6"
    },
    title: "Bachelor of Engineering [B.Eng] (Chemical Engineering)",
    info: "Bachelor of Engineering inChemical Engineeringat McGill Universityallows students to complete this programin 3years.Students needto complete 120credits successfully to graduate from this Chemical Engineeringprogram.Students are exposed to both theoretical and practical issues of both hardware and software in well-equipped laboratories.The Bachelor's in Chemical Engineeringoffers advanced training in the critical, historical, and theoretical analysis of:Heat and Mass TransferThermodynamicsFoundations of Fluid MechanicsChemical Reaction EngineeringAdvanced Biochemical EngineeringComputational MethodsIn addition to technical complementary courses, students in the Chemical Engineeringprogram take general complementary courses in social sciences, management studies, and humanities.The discipline of chemical engineering is distinctive in being based equally on physics, mathematics, and chemistry.The application of these three fundamental sciences is basic to a quantitative understanding of the process industries.Those with an interest in the fourth major science, biology, will find several courses in the Chemical Engineering curriculum which integrate aspects of the biological sciences relevant to process industries such as food processing, fermentation, and water pollution control.The students to faculty ratio for this Chemical Engineeringprogram at McGill Universityis 17:1.The job opportunities after this Chemical Engineeringprogram that students get at McGill University are:Analytical chemistEnergy managerEnvironmentalengineerManufacturingengineerMaterialsengineeretc., with anaverage salary of 34,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission at McGill University in this Chemical Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission at Chemical EngineeringProgram.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },
  {
    _id: {
      $oid: "63d2b7a30c1cb06c264742b8"
    },
    title: "Bachelor of Engineering [B.Eng] (Electrical Engineering)",
    info: "Bachelor of Engineering inElectrical Engineeringat McGill Universityallows students to complete this programin 4years.Students needto complete 120credits successfully to graduate from this Electrical Engineeringprogram.Students are exposed to both theoretical and practical issues of both hardware and software in well-equipped laboratories.The Bachelor's in Electrical Engineeringoffers advanced training in the critical, historical, and theoretical analysis of:Bioelectrical EngineeringTelecommunications and Signal ProcessingIntegrated Circuits and SystemsNano-Electronic Devices and MaterialsComputational ElectromagneticsIn addition to technical complementary courses, students in the Electrical Engineeringprogram take general complementary courses in social sciences, management studies, and humanities.Electrical engineers create, design, build and operate the electrical systems that power homes, schools, and businesses.They are also behind the technology used for cell phones, video games, automation, and robotics.Electrical engineers are creative thinkers who are good at math and physics and enjoy working with computers and in labs.They have strong communication skills that are useful since electrical engineers often work in teams with civil or mechanical engineers or architects.The students to faculty ratio for this Electrical Engineeringprogram at McGill Universityis 16:1.The job opportunities after this Electrical Engineeringprogram that students get at McGill University are:Power EngineerElectrical EngineerTransit Technology Systems EngineerIndustrial Electronics SpecialistMedical Device Developer, etc., with anaverage salary of 37,250 USD.",
    fees: "YearYear 1Year 2Year 3Year 4Tuition Fees₹3362666₹3362666₹3362666₹3362666Health Insurance₹60649₹60649₹60649₹60649Miscellaneous expenses₹65324₹65324₹65324₹65324Other Fees₹62592₹62592₹62592₹62592Total Fees₹3423315₹3423315₹3423315₹3423315",
    exams: "Students must meetthe following requirements for admission at McGill University in this Electrical Engineeringprogram:A- average in grades 10, 11 and 12A- in each prerequisite math and scienceACT 31(Maths & Science subscores ≥ 29, others ≥ 27);orSAT: EB Read & Writing 700, Math 700andSubject Tests: 680 in each subjectStudents must have basic knowledge inPre-calculus, Chemistry, and PhysicsIndian Student Eligibility:Indian students need to maintain an overall average of 60% in their 12th grade for admission at McGill University'sElectrical EngineeringProgram.Along with the minimum eligibility requirements, international students hailing from non-English speaking countries need to prove English proficiency through IELTS/TOEFL/any equivalent test.The above requirements are the minimum requirements and do not guarantee admission. The admissions committee will consider all evidence in the file and decide. To know more about the requirem….",
    __v: 0
  },




]